# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./src/Frontend

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        #cache: 'npm'
    - name: Clean slate
      run: npm ci
      working-directory: ${{env.working-directory}}
    - name: Install quasar
      run: npm install -g @quasar/cli
      working-directory: ${{env.working-directory}}
    - name: Build
      run: quasar build
      working-directory: ${{env.working-directory}}
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: src/Frontend/dist/spa/ # The folder the action should deploy.
